steps:
  - name: 'gcr.io/hackaton2019-242912/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=https://sonar.jbtteam.playpit.net'
    - '-Dsonar.login=5786c280e29e081c445cf943c61cb20eef616fc7'
    - '-Dsonar.projectKey=currency_service_js'
    - '-Dsonar.sources=src'
  #step 1
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/hackaton2019-242912/currencyservice', '.']
  #step 2
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml', '-n', '$_ENVIRONMENT']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=europe-west4'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hackaton2019-gke-cluster'
    id: deploy
  #step 3
  - name: gcr.io/hackaton2019-242912/jmeter:latest
    args:
    - '-n'
    - '-t'
    - 'jmeter-config.jmx'
    waitFor:
    - deploy
images: ['gcr.io/hackaton2019-242912/currencyservice']
tags: ['test_cloud_build']
